server:
  http_port: ":8080"

database:
  master:
    host: "db"
    port: "5432"
    user: "postgres"
    pass: ""
    name: "events_db"
    ssl_mode: "disable"

    slaves: [ ]

    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: 30m

jwt:
  secret: "very-long-secret"
  ttl: "24h"

email:
  smtp_host: "smtp.mailtrap.io"
  smtp_port: "587"
  username: "smtp_user"
  password: "smtp_pass"
  from: "example@example.com"